# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/lab-3-5/pmod_kypd/pmod_kypd.srcs/sources_1/bd/kypd_design/ip/kypd_design_processing_system7_0_0_1/kypd_design_processing_system7_0_0.xci
# IP: The module: 'kypd_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/lab-3-5/pmod_kypd/pmod_kypd.gen/sources_1/bd/kypd_design/ip/kypd_design_processing_system7_0_0_1/kypd_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/lab-3-5/pmod_kypd/pmod_kypd.srcs/sources_1/bd/kypd_design/ip/kypd_design_processing_system7_0_0_1/kypd_design_processing_system7_0_0.xci
# IP: The module: 'kypd_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/lab-3-5/pmod_kypd/pmod_kypd.gen/sources_1/bd/kypd_design/ip/kypd_design_processing_system7_0_0_1/kypd_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
