# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/kypd_design/kypd_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_design || ORIG_REF_NAME==kypd_design} -quiet] -quiet

# IP: bd/kypd_design/ip/kypd_design_PmodKYPD_0_0_1/kypd_design_PmodKYPD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_design_PmodKYPD_0_0 || ORIG_REF_NAME==kypd_design_PmodKYPD_0_0} -quiet] -quiet

# IP: bd/kypd_design/ip/kypd_design_processing_system7_0_0_1/kypd_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_design_processing_system7_0_0 || ORIG_REF_NAME==kypd_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/kypd_design/ip/kypd_design_ps7_0_axi_periph_0_1/kypd_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==kypd_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/kypd_design/ip/kypd_design_rst_ps7_0_100M_0_1/kypd_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==kypd_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/kypd_design/ip/kypd_design_auto_pc_0_1/kypd_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_design_auto_pc_0 || ORIG_REF_NAME==kypd_design_auto_pc_0} -quiet] -quiet

# XDC: /home/user/lab-3-5/pmod_kypd/pmod_kypd.gen/sources_1/bd/kypd_design/kypd_design_ooc.xdc
